backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: ferrari-tran/ferrari-portfolio

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "works" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}_{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Blog Creater Name", name: "blogerName", widget: "string", required: true}