backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: ferrari-tran/ferrari-portfolio
  site_url: "thuytp.com"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "static/works" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "work/{{slug}}"
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: "authorName", widget: "string", required: true}